export const LANDING = '/';
export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const LIST = '/list';
export const HOME = '/home';
export const ACCOUNT = '/account';
export const ADMIN = '/admin'; //cannot hav ./ either ;(
export const PASSWORD_FORGET = '/pw-forget';
export const PASSWORD_CHANGE = '/pw-change'; //you NEED THE '/' ermagurd
export const WOMEN = '/women';
export const GIRL = '/girl'
export const MEN= '/men'